### ISSUE TITLE
Detected blocking call to open inside the event loop 

### ISSUE THREAD

**Issue by larronni** [mrk-its/homeassistant-blitzortung#106]
Detected blocking call to open inside the event loop by custom integration 'blitzortung' at custom_components/blitzortung/mqtt.py, line 98: import paho.mqtt.client as mqtt # pylint: disable=import-outside-toplevel (offender: /usr/local/lib/python3.12/ctypes/util.py, line 276: with open(filepath, 'rb') as fh:), please create a bug report at https://github.com/mrk-its/homeassistant-blitzortung/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 447, in _async_setup_component await asyncio.gather( File "/usr/src/homeassistant/homeassistant/setup.py", line 449, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/blitzortung/__init__.py", line 78, in async_setup_entry coordinator = BlitzortungCoordinator( File "/config/custom_components/blitzortung/__init__.py", line 201, in __init__ self.mqtt_client = MQTT( File "/config/custom_components/blitzortung/mqtt.py", line 98, in __init__ import paho.mqtt.client as mqtt # pylint: disable=import-outside-toplevel

**Comment by mrk-its** [comment]
Thanks, just noticed it on 2024.6.1, will take a look on it soon. Thanks!

**Comment by jhemak** [comment]
Just started having this issue on 2024.6.4

**Comment by jbonzey** [comment]
Same problem here starting on 6.4
