### ISSUE TITLE
The version in the `manifest.json` file is not current

### ISSUE THREAD

**Issue by bieniu** [mrk-its/homeassistant-blitzortung#108]
Integration version: `1.3.4`

The version field in the manifest file is not updated, which causes the incorrect version number to be displayed in the HA interface

https://github.com/mrk-its/homeassistant-blitzortung/blob/ddcd634376a1d237373e01548d044ebec0a9ef99/custom_components/blitzortung/manifest.json#L16

![obraz](https://github.com/mrk-its/homeassistant-blitzortung/assets/478555/07f7c725-b286-47fd-a89c-0a4889c5425e)

**Comment by mrk-its** [comment]
Good catch, thanks!
