### ISSUE TITLE
Blitzortung is a service not a device so a device_info property is unnecessary

### ISSUE THREAD

**Issue by bieniu** [mrk-its/homeassistant-blitzortung#11]
`device_info` property is used for devices, not services so these lines:
https://github.com/mrk-its/homeassistant-blitzortung/blob/master/custom_components/blitzortung/sensor.py#L124-L131
are unnecessary.

**Comment by mrk-its** [comment]
Is there any official HA policy forbidding that? I really like device info card grouping all sensors together and allowing for easy addition to lovelace panel:
![Screenshot from 2020-08-02 13-06-54](https://user-images.githubusercontent.com/920204/89121689-3919f300-d4c1-11ea-9f9a-0d944f010d2f.png)

**Comment by bieniu** [comment]
I understand your point. It's also not possible to use device automation without device info.
There is no official policy forbidding that (at least I didn't find it) but when reviewing new integration device_info is marked as an item for removal.
Will you try to add this integration to the official repository? It's a very good integration and in my opinion it would be good if it was officially available in Home Assistant.

**Comment by mrk-its** [comment]
> Will you try to add this integration to the official repository? It's a very good integration and in my opinion it would be good if it was officially available in Home Assistant.

Thanks for kind words. Yes, I'll try to add this to HA repository. But before that I'll try to find few volunteers to help hosting it. Currently I'm running single small MQTT proxy on very small, dedicated VPS. It would be great to create pool of such proxies and distribute load between them (even with simple DNS load balancing) The good thing is hosting costs seems to be not measurable with 500 clients connected all the time - it seems possible to convince some users of this integration with spare resources on their servers to help with hosting it.

**Comment by bieniu** [comment]
HA team uses Azure Cloud for CI. Maybe this cloud could be used for the MQTT proxy if the integration will be in HA repo. You can ask on Discord if such things are even possible.

**Comment by bieniu** [comment]
I asked for `device_info` property in developer chat. It is allowed using it for service-based integrations but you need to add `entry_type: service`.

https://github.com/home-assistant/core/blob/dev/homeassistant/components/adguard/__init__.py#L201

**Comment by mrk-its** [comment]
Done: https://github.com/mrk-its/homeassistant-blitzortung/commit/d76a2951ba1a48ad635bf69c9f1c75676aa4ba66

Thanks!
