### ISSUE TITLE
Blocking Call to listdir (Blitzortung)

### ISSUE THREAD

**Issue by cloudbr34k84** [mrk-its/homeassistant-blitzortung#116]
Cause: Similar to the Plex error, the blitzortung integration is making a blocking call using os.listdir(directory) inside the event loop, specifically in the mqtt.py file.
Solution:
l need to refactor this part of the code to use an asynchronous approach.

**Comment by mrk-its** [comment]
@cloudbr34k84 can you check again for this error on latest 1.3.6 release?

**Comment by cloudbr34k84** [comment]
@mrk-its yeah cant see anything in the logs now!
