### ISSUE TITLE
Shouldn't azimuth be 0..360° ? 

### ISSUE THREAD

**Issue by Syralist** [mrk-its/homeassistant-blitzortung#12]
The azimuth sensor gives values -180..180°. Wikipedia says azimuth is 0..360° and for example the lovelace compass card also expects only positive values. 
Was this range a deliberate choice? Maybe I'm missing something? 
EDIT: l only just read #9 after opening this, so maybe it's not a problem after all. 😎

**Comment by mrk-its** [comment]
The only reason of -180..180 range was human readability - for example E is 90°, W is -90° and so on. In terms of math it also seems correct as -90° angle is the same as 270°. But if it is common practice to use 0..360 and nobody uses negative values it should be changed :)

**Comment by Syralist** [comment]
I agree in terms of math and atan the values are +/- pi. ;) As for common practice or readability I only read the Wikipedia article. 

Now that the compass card accepts negative values I wont be looking at the raw sensor value anymore.

**Comment by sgofferj** [comment]
Depends what you want to show. In geospatial applications, navigation, etc. 0-360 is used, so everybody used to work with a compass will probably stumble over -180 - 180. Math-buffs would probably rather see -180 - 180.

**Comment by tubalainen** [comment]
I do agree, please make it 0-360 degrees (Azimuth). 
So that it logically makes sense to merge in automations with for example wind direction.

👍

**Comment by mrk-its** [comment]
Just fixed. Thanks everyone for feedback! Closing.
