### ISSUE TITLE
Entities aren't purged after a thunderstorm

### ISSUE THREAD

**Issue by Nickduino** [mrk-its/homeassistant-blitzortung#134]
I read https://github.com/mrk-its/homeassistant-blitzortung/issues/13

In which you say:
>  older entities will be removed.

My config is:

![image](https://github.com/user-attachments/assets/f09bddaf-1cf2-4ebc-9116-40d82e8a2c0f)

There was a thunderstorm yesterday, the counter has been at 0 since 5:45 this morning (it is 11:25):

![image](https://github.com/user-attachments/assets/5a88e5f9-3e54-47c1-9c4e-e884d62b614e)

But I still have thousands (I track them at two locations, the storm was seen at both) of entities:

![image](https://github.com/user-attachments/assets/0d5991bf-049f-4eef-b5c7-a531d68b7d55)

Also, I set the max number of tracked lightnings at 1000 and the counter went to 1909?

**Comment by bieniu** [comment]
Which version of the integration?

**Comment by Nickduino** [comment]
1.3.7

![image](https://github.com/user-attachments/assets/9f2f8413-a68a-4014-8e6c-5a139ea03f11)
