### ISSUE TITLE
Updated to 1.3.8-b3 and another service popped up

### ISSUE THREAD

**Issue by Nickduino** [mrk-its/homeassistant-blitzortung#136]
I updated to the v1.3.8-b3 and another Blitzortung service popped up:

![image](https://github.com/user-attachments/assets/a44a7821-d8d9-44e9-9a38-d874ae78e99a)

This is the "historical" service (with, for example `sensor.blitzortung_lightning_counter`):

![image](https://github.com/user-attachments/assets/ff083344-916f-4c9d-bbc6-ffe39df5b554)

(All are unavailable. The "Blitzortung Clermont min distance" is a statistic helper, it gives me the closest lightning strike in the last hour)

And the new one (now `sensor.blitzortung_lightning_counter_2`):

![image](https://github.com/user-attachments/assets/9074c955-27e0-4498-9a08-6c76b5ac8fb9)

What's weird is that I have another service (for another location. To be clear, I should have two services in total and I have three at the moment) with the same helper that also existed before the update to the beta version and this one kept working : 

![image](https://github.com/user-attachments/assets/21b5b147-82cd-4a88-aa8b-3501f38fdc44)

How can I resolve that?

**Comment by bieniu** [comment]
I just checked the migration process

- from `1.3.5` to `1.3.8-b3`
- from `1.3.6` to `1.3.8-b3`
- from `1.3.7` to `1.3.8-b3`

 and I cannot reproduce your issue. Are you 100% sure you haven't used a beta release before?
 
 To resolve the issue you need to remove and re-add the integration configuration.

**Comment by Nickduino** [comment]
> and I cannot reproduce your issue. Are you 100% sure you haven't used a beta release before?

Absolutely sure. I installed the integration fairly recently (a few weeks), I discoverer the switch to activate beta releases very recently (a few days ago), turned it on, then updated to beta for the first time ever.

Note that the issue didn't appear on the second service (for another location). It might be random or it might appear when you have more than one location? Or appear only if you have a helper using one of the sensors? Or a combination of all?


> To resolve the issue you need to remove and re-add the integration configuration.

I think I'm going to delete the old service and then rename the entities of the new one from `sensor.blitzortung_lightning_counter_2` to `sensor.blitzortung_lightning_counter` and see if my dashboard accepts that. Unless you see an issue with this?

**Comment by bieniu** [comment]
Could you show me the contents of the /config/.storage/core.device_registry file? Or the part of that file that contains the entries for Blitzortung.

_**Before doing anything with that file, make a backup. Corrupting that file can cause HA to stop starting.**_

> Unless you see an issue with this?

You cannot remove a service, you can remove the configuration (config entry) to which both services are assigned.

**Comment by Nickduino** [comment]
The only entry I have for Blitzortung is in the deleted devices

```
{
  "version": 1,
  "minor_version": 8,
  "key": "core.device_registry",
  "data": {
    "devices": [
      {"area_id":null,"config_entries":["f544410ab1f4c3331b4794eb5b65dd89"],"configuration_url":null,"connections":[],"created_at":"1970-01-01T00:00:00+00:00","disabled_by":null,"entry_type":"service","hw_version":null,"id":"c5>
      [...]
      {"area_id":null,"config_entries":["3fad6a756ea08affb4823e3245b6b797"],"configuration_url":"homeassistant://hacs/repository/831739499","connections":[],"created_at":"2024-10-24T12:15:36.523432+00:00","disabled_by":null,"en>
    ],
    "deleted_devices": [
      {"config_entries":[],"connections":[],"created_at":"2024-09-25T16:55:21.189384+00:00","identifiers":[["blitzortung","Blitzortung Test"]],"id":"9c2eff2b4649091bdefd91e862060f9e","orphaned_timestamp":1727283751.4605598,"mod>
      {"config_entries":["3fad6a756ea08affb4823e3245b6b797"],"connections":[],"created_at":"2024-09-26T16:03:05.758190+00:00","identifiers":[["hacs","269011342"]],"id":"70fe4a1a0c4e65a8cb918145b17665cd","orphaned_timestamp":nul>
      {"config_entries":[],"connections":[],"created_at":"1970-01-01T00:00:00+00:00","identifiers":[["fastdotcom","81662d3de5bd21bd712255f7b6a34298"]],"id":"b970f4a094a007c97eb2b226636b3b5e","orphaned_timestamp":1729597725.4133>
    ]
  }
}
```

**Comment by bieniu** [comment]
I tried to reproduce your problem today when the integration reports lightnings (during a storm) and I failed. Each time the migration went correctly and the second service was not created.

Do you sometimes see errors in HA log about blocking the event loop? Blocking the event loop can lead to the integration initialization being delayed and not everything working as it should.

**Comment by Nickduino** [comment]
> I tried to reproduce your problem today when the integration reports lightnings (during a storm) and I failed.

Thank you, it's a real treat to have the someone so proactive about fixing issues. I'll keep answering your questions if you have any but I'm gonna close the issue and classify it as a freak incident. I'll let you know if it happens again, though.


> Do you sometimes see errors in HA log about blocking the event loop?

Nope

![image](https://github.com/user-attachments/assets/268f1965-8d52-4e36-9ea9-2bedcc94c6a2)
