### ISSUE TITLE
FR: Differentiate  geo_location entities by service

### ISSUE THREAD

**Issue by Nickduino** [mrk-its/homeassistant-blitzortung#137]
I have two services for two locations. I'd like to display a small map for each but if I code the map card with `geo_location_sources: blitzortung` all lightning strikes from both "detectors" will be shown at the same time (with a pretty low zoom level to fit both, which makes the cards pretty much unreadable if there are storms at both locations)

**Comment by bieniu** [comment]
I'm afraid that's impossible. The only thing you could do is clone the integration and give it a different domain than `blitzortung`.

**Comment by Nickduino** [comment]
Alright, thanks
