### ISSUE TITLE
[homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike

### ISSUE THREAD

**Issue by papo-o** [mrk-its/homeassistant-blitzortung#17]
hello , 
i have a lot of this error in my log when  thunderstorm is near my house
![image](https://user-images.githubusercontent.com/25136535/93666161-26ad4600-fa7c-11ea-8b48-6fa3d0d0f29e.png)
any idea?

**Comment by mrk-its** [comment]
This is likely due to how the entity IDs are created - currently they are based only on lat / lon coordinates and it seems it is not enough. Adding timestamp should help, maybe I'll need to hash it (because it is quite long already). I'll fix it soon, stay tuned!

**Comment by locorotondo-gitter** [comment]
Hi.
 First of all; thank you for this piece of programming! I really like it. 

Is there any update on this buglet (it does not seem to impact the functionality as far as I can tell)? Yesterday we had a bunch of thunderstorms nearby and the logfiles were swamped with thousands of the messages that @papo-o mentioned. (at the end of the evening there were well over 18k registered lightning strikes in the area ;-)). 

LIke I said; it does not seem to impact functionality (unless I miss something), so if you leave it "as is" I can totally be happy with that. :-)

Stay safe, stay healthy!

**Comment by attila123456** [comment]
Same here, 800+ occurrences of the above error after a thunderstorm. Any chance of reopening the issue? Thanks!

**Comment by umrath** [comment]
#9ef18f7 does not fix the issue.

**Comment by AdmiralStipe** [comment]
Issue still present, please re-open!

**Comment by Bob-Technicien-pro** [comment]
> Issue still present, please re-open!

for me too
