### ISSUE TITLE
Error fetching blitzortung data: status: 401

### ISSUE THREAD

**Issue by ercsey** [mrk-its/homeassistant-blitzortung#2]
Hello

Another error message. Is it possible that blitzortung.org put an authentication on http://data"?".blitzortung.org/Data/Protected/last_strikes.php url?

Thanks for your answer.

**Comment by mrk-its** [comment]
I'll take a look, thanks!

**Comment by mrk-its** [comment]
@ercsey I've refactored whole thing a bit.
It receives data from Blitzortung via websocket now, so updates will be realtime. Additionally component connects to proxy MQTT server, reducing Blitzortung traffic.
Let me know if it works for you now.

**Comment by ercsey** [comment]
I can confirm that the status 401 error is gone. However still have to wait for some lightnings to see if working without any error.
Thank you very much for this great  component. Really appreciate it.

**Comment by mrk-its** [comment]
@ercsey to test you can simply add other instance of this integration with bigger radius (like 1000 km or so) :)
