### ISSUE TITLE
Please add version to manifest.json

### ISSUE THREAD

**Issue by firstof9** [mrk-its/homeassistant-blitzortung#24]
New requirements for custom components.

`2021-03-01 12:28:29 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'blitzortung'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'blitzortung'`

**Comment by S-Przybylski** [comment]
In 2021.6 is will be disabled if not updated.
see log of 2021.5dev:  WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'blitzortung'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'blitzortung'

**Comment by S-Przybylski** [comment]
I think the change is easy to include (example). Add:
´´´´
  "homeassistant": "2021.3.0",
  "version": "v2.0"
´´´´
Resulting manifest.json:
´´´´
{
  "domain": "blitzortung",
  "name": "Blitzortung",
  "config_flow": true,
  "documentation": "https://github.com/mrk-its/homeassistant-blitzortung",
  "issue_tracker": "https://github.com/mrk-its/homeassistant-blitzortung/issues",
  "requirements": ["paho-mqtt>=1.5.0"],
  "after_dependencies": [],
  "dependencies": [
    "persistent_notification"
  ],
  "codeowners": [
    "@mrk-its"
  ]
 "homeassistant": "2021.3.0",
  "version": "v2.0"
}
´´´´
Could you please update the repo?

**Comment by frank-ydf** [comment]
same here... I try to bypass the error by adding

`"version": "1.1.0",`

in the manifest file but HassOS not find Blitzortung in the integrations so, can't use that fantastic & useful integration. I'm quite disappointed :(

**Comment by mrk-its** [comment]
Thanks guys, I totally missed it out. Taking a look

**Comment by frank-ydf** [comment]
> Thanks guys, I totally missed it out. Taking a look

thank to you mate, now it works very well again!!!
