### ISSUE TITLE
Getting MQTT Error

### ISSUE THREAD

**Issue by craigmate** [mrk-its/homeassistant-blitzortung#26]
HI

I have been using this custom component for a while and haven't had any issues, however lately I have noticed that it stops working

The errors in the event log are 
[custom_components.blitzortung.mqtt] Failed to connect to MQTT server due to exception: [Errno -3] Try again

I didn't think this used MQTT, as there isn't an option to point it to a broker, unless I am wrong...

**Comment by mrk-its** [comment]
I've just confirmed that MQTT server is working and a lot of clients are connected now (but it looks like there was some downtime 20 jun, ~0:00 UTC)  What HA version are you using (maybe you did upgrade recently)?

**Comment by craigmate** [comment]
Thanks for the quick reply..  I checked if my Adguard or PiHole were doing any blocking, but I couldn't see any
I did find that blitzortung.ha.sed.pl was been forwarded successfully to the upstream DNS.

However when I tried to ping or use nslookup to resolve it, it doesn't resolve to an IP.. 
I tried using a few DNS servers and nothing worked. Not sure if that is relevant or not..

I haven't updated HA lately.  I am still on  core-2021.5.5

**Comment by mrk-its** [comment]
> However when I tried to ping or use nslookup to resolve it, it doesn't resolve to an IP..
> I tried using a few DNS servers and nothing worked. Not sure if that is relevant or not..
> 
Ha - so this is strangest part, this domain should definitely resolve to IP. Could you show output of:
```dig blitzortung.ha.sed.pl```

**Comment by craigmate** [comment]
OK,  Now it is resolving.  Below is the dig command
; <<>> DiG 9.16.15 <<>> blitzortung.ha.sed.pl
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25678
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 689d9c47e346e087 (echoed)
;; QUESTION SECTION:
;blitzortung.ha.sed.pl.         IN      A

;; ANSWER SECTION:
blitzortung.ha.sed.pl.  60      IN      CNAME   ec2-35-158-104-63.eu-central-1.compute.amazonaws.com.
ec2-35-158-104-63.eu-central-1.compute.amazonaws.com. 60 IN A 35.158.104.63

;; Query time: 4071 msec
;; SERVER: 172.30.32.3#53(172.30.32.3)
;; WHEN: Mon Jun 21 19:34:29 AEST 2021
;; MSG SIZE  rcvd: 217


I also was able to resolve it from my windows desktop as well
Default Server:  pi-hole
Address:  192.168.1.20

> blitzortung.ha.sed.pl
Server:  pi-hole
Address:  192.168.1.20

Non-authoritative answer:
Name:    ec2-35-158-104-63.eu-central-1.compute.amazonaws.com
Address:  35.158.104.63
Aliases:  blitzortung.ha.sed.pl

And it now appears to be working.. Very strange...

**Comment by mrk-its** [comment]
Maybe it was some problem with DNS provider for my domain - please let me know if it repeats.
