### ISSUE TITLE
Entity id already exists - ignoring: geo_location.lightning_strike_ < HASH> 

### ISSUE THREAD

**Issue by gdschut** [mrk-its/homeassistant-blitzortung#28]
I like your addon, nice work!

Despite solved older issues i got plenty of messages like these in my logfiles after a thunderstorm:

> 2021-06-28 15:23:40 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_02f45435d99207aa58d31aa0bb35fcb498e17cc3
> 2021-06-28 15:23:53 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_0049e3f83b4638136157a6d365d63e084f1c0cfd
> 2021-06-28 15:24:22 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_898acf9a3258e7b522bd7393a2b22949469074cd
> 2021-06-28 15:24:22 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_fb1317a8ea5525eea4408fe0b18d0d7a6690a197
> 2021-06-28 15:24:23 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_687b5817bc01c5705e9edfaa3b39b2ea5edb1132
> 2021-06-28 15:24:23 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_a3bbc5b73f4fd157136ab35995fa28c93e2d3cb0
> 2021-06-28 15:24:23 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_d91e62dbcef7465175796958f5c09ae97ee9b662
> 2021-06-28 15:24:24 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_2b2fc11566ff678c8e21f5cec1ee184520a468b5
> 2021-06-28 15:24:25 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_d259b39c2c906a41df550029bf5be9627eab9486
> 2021-06-28 15:24:25 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_1619de84f05f2cbd2d533b2991b7d26630820c7c
> 2021-06-28 15:24:25 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_7cc3a8e7033b25ce5631bf0f29ad5eca2eb1595f
> 2021-06-28 15:24:25 ERROR (MainThread) [homeassistant.components.geo_location] Entity id already exists - ignoring: geo_location.lightning_strike_85c0755db4454faf9f2126abbc64dba569574417

Still the addon seems to work properly , although I cannot check if I am missing lightning strikes or not...
After a couple of minutes my Map view in HA crashes, but Im not sure if this is related. Before I used this addon I did not use the Map at all.

**Comment by JeeCee1** [comment]
Same here @mrk-its, would you be so kind to have a look at it, thanks!!
Thanks for a nice integration though!!

**Comment by kloggy** [comment]
I've always had these messages too.
I'm not sure if they are causing any problems though apart from clogging up the log file?

**Comment by AdmiralStipe** [comment]
Really annoying issue, floods my log file whenever lightnings are detected nearby. Is it even dealt with?

**Comment by jokerigno** [comment]
same issue here

**Comment by stalakerob** [comment]
I also have this issue. Looks like that this issue is open since almost 1 year .

**Comment by Bob-Technicien-pro** [comment]
same issue here

**Comment by Foguet** [comment]
Hi. Same issue here :(
