### ISSUE TITLE
No integration added after install through HACS

### ISSUE THREAD

**Issue by TASSDevon** [mrk-its/homeassistant-blitzortung#29]
I've just installed this integration through HACS but it is not showing up on the integration page nor any entities are created. No output in the log file.

My installation: 

HA version 2021.6.5
HACS version 1.13.2

**Comment by Raphidev** [comment]
Did you use 64bit version of HA ?

**Comment by TASSDevon** [comment]
I'm using the containerized version on an rpi4

**Comment by plumped** [comment]
Same here. Nothing happens after installation trough HACS on Docker Container Hassio

**Comment by Raphidev** [comment]
Same on my 64bit Core installation. Folder is created correctly but the Integration is not showed.
I will try the 32bit

**Comment by Raphidev** [comment]
Hi @all
 are your sure you installed it twice ?
Once via Hacks then reboot and reinstall it like alle other in System / integrations ?

I think this is the solution

**Comment by TASSDevon** [comment]
What do you mean with reinstall it like all other? For me it doesn't appear in the system / integration page so there is no reinstall option to select.

**Comment by plumped** [comment]
> Hi @ALL
> are your sure you installed it twice ?
> Once via Hacks then reboot and reinstall it like alle other in System / integrations ?
> 
> I think this is the solution

Not sure what you mean with "twice" exactly. Manuall config in configuration.yaml + HACS?

**Comment by myriadtim** [comment]
I'm also having this problem on the containerized version of HA.
I installed via HACS, custom_components file is present.
I am on HA 2021.6.6 / HACS 1.13.2.
Other custom components work.
After a hard restart of the docker container component was available in configuration/integrations.

**Comment by plumped** [comment]
> 
> 
> I'm also having this problem on the containerized version of HA.
> I installed via HACS, custom_components file is present.
> I am on HA 2021.6.6 / HACS 1.13.2.
> Other custom components work.
> After a hard restart of the docker container component was available in configuration/integrations.

Do you still have the Problem @myriadtim or is it solved on your side? A hard reset of the container is not working for me

**Comment by plumped** [comment]
Ok i have it!

After installation use the Button Insert Integration on the integration page. In other words install manually an integration with the + Button 
![grafik](https://user-images.githubusercontent.com/41291962/127065623-b98de764-0b80-4245-9ebc-6a57c5989d00.png)

Hope this helps @TASSDevon

**Comment by TASSDevon** [comment]
Indeed, it appears in the 'add integrations' list after a full container restart.
I'm leaving this issue open since this should be fixed at some point.

**Comment by aavosnl** [comment]
Several installs done, with the same restart and reboot. It don't seems to work.

**Comment by DrewXT** [comment]
I hate being a "me too" but I've got an even stranger installation observation - I have two instances running on VMware - both Supervised, and my main HA instance, also Supervised on a NUC, and I can install and remove the add-on on both the VMware instances, but not on the NUC... 

I've installed manually, and via HACS, both of which populate the custom_components folder, yet I have nothing when I try to add the Integration

**Comment by DrewXT** [comment]
Just been through the same scenario as @agaudi66 - eventually the Integration appeared in Integrations .... I've been unable to debug the why though...

**Comment by DaleGervais** [comment]
Unable to prepare setup for platform blitzortung.sensor: Platform not found (cannot import name 'DeviceEntryType' from 'homeassistant.helpers.device_registry' (/snap/home-assistant-snap/364/lib/python3.8/site-packages/homeassistant/helpers/device_registry.py)).
Home Assistant Core 2021.8.8  Loaded 
Path to configuration.yaml: /var/snap/home-assistant-snap/364 
HACS version 1.15.2
loaded by Snap on Fedora 33 Linux
I simply allowed the latest upgrade of Blitzortung to install and now I get the above error.  I have rebooted the linux OS and reloaded,deleted, and reloaded Blitzortung multiple times,
Can I fall back to an earlier version of Blitzortung?  How do I attempt a Manual install?  Any documentation to manually setup sensors?

Thanks for any assistance.

**Comment by xtro83** [comment]
hello 
I can't install a custom repository, the box remains grayed out  ( hacs 1.26.2) , 
can you help me ?  thank you 
![2022-11-24_102845](https://user-images.githubusercontent.com/36260342/203748122-ebf74701-d12c-4e4b-aa2d-53784631aa76.jpg)
