### ISSUE TITLE
unable to find integration

### ISSUE THREAD

**Issue by Christianb233** [mrk-its/homeassistant-blitzortung#3]
Hello, I thank you for this interesting integration. ! :-) But unfortunately, after : 
- puting contents of your custom_component/blitzortung directory inside custom_components dir, and restarting Home Assistant, I don't see anything by searching for Blitzortung on Configuration/Integrations page :-)

I have tried placing custom_component/blitzortung directory inside custom_components dir, and restarting Home Assistant
But I have this error (and nothing by searching for Blitzortung on Configuration/Integrations page)  :
`2020-07-05 18:11:25 ERROR (SyncWorker_2) [homeassistant.loader] Error parsing manifest.json file at /config/custom_components/blitzortung/manifest.json: Expecting value: line 6 column 1 (char 5)`

For information, I have installed Home Assistant in a docker on a Rapsberry PI (Rasbian)

I thank you in advance for your help,
Best regards.
Christian

**Comment by mrk-its** [comment]
Please make sure you are using latest version - I've just double checked that `manifest.json` is correct. Also currently there is no `custom_component/blitzortung` directory, I've renamed it to `custom_components/blitzortung` recently.
 The other option is to use HACS - you can add this extension as custom repository (I'm also trying to add this component to default HACS repo).

**Comment by mrk-its** [comment]
Also it would be helpful to see contents of your `custom_components/blitzortung/manifest.json` - the error you provided simply says  that this file is not valid json

**Comment by Christianb233** [comment]
Thank you for your answer, 
I have realized by investigating that my copy-paste of files was wrong; I have corrected that and the process goes well :-)
Just a last question about the post-treatment : I see 4 entities, but how do you use these entities for a good card in lovelace ?
Thank you again for these integration

**Comment by mrk-its** [comment]
You can ignore "Clients Connected" Sensor - it is for tracking how many clients (HA instances) are connected to mqtt server, I'll probably remove it in future versions.

Distance / Azimuth Sensors should be quite useful, they show distance and direction to latest lightning in you area (Azimuth 0 means norht, 90 means east, -90 is west). The history graph of these sensors also seems to be useful, it is easy to see whether the storm is approaching and from what direction. Number of lightnings also clearly shows intensity of the storm. 

All sensor values are reset after two hours of inactivity (shows as unavailable).
