### ISSUE TITLE
Unknown distance and azimuth

### ISSUE THREAD

**Issue by larronni** [mrk-its/homeassistant-blitzortung#30]
If there has been no lightning today, both distance and azimuth comes up with state "unknown". Can it be changed to 0 instead ?

**Comment by MarkusFelix** [comment]
Yes please - currently I need to convert the value via a template sensor just so re-write `unknown` to 0, which seems silly to me.

**Comment by mrk-its** [comment]
IMHO `unknown` is better than 0 in such cache (it simply means that there is no lightning while 0 is valid value for distance / azimuth). Closing.
