### ISSUE TITLE
No connection to Blitzortung

### ISSUE THREAD

**Issue by ebonzl** [mrk-its/homeassistant-blitzortung#31]
Has not been working here for some time: ERROR (MainThread) [custom_components.blitzortung.mqtt] Failed to connect to MQTT server due to exception: timed out
Are MQTT servers changed or service ceased?

**Comment by chatainsim** [comment]
Same here, I don't know how it's working.
is it internal HA mqtt or Blitz mqtt ?
Thanks

**Comment by chatainsim** [comment]
Hello, can you help us on this ?
Thank you. No change with latest version 1.1.2

**Comment by tomlut** [comment]
Still connecting from here. What is your HA DNS server set to?

Settings -> System -> Network.

**Comment by chatainsim** [comment]
Ok, my bad. I was using my old DNS server. Changed to new one and it's working now.
