### ISSUE TITLE
Beta 2021.12.0b0 Error

### ISSUE THREAD

**Issue by Wibias** [mrk-its/homeassistant-blitzortung#34]
Entity sensor.blitzortung_lightning_distance (<class 'custom_components.blitzortung.sensor.DistanceSensor'>) implements device_state_attributes. Please report it to the custom component author.

Entity sensor.blitzortung_lightning_azimuth (<class 'custom_components.blitzortung.sensor.AzimuthSensor'>) implements device_state_attributes. Please report it to the custom component author.

Entity sensor.blitzortung_lightning_counter (<class 'custom_components.blitzortung.sensor.CounterSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by heikkih** [comment]
I've added two fixes in PR #35 and PR #36 for this issue.

**Comment by Wibias** [comment]
Yea seems that he is not active anymore, looking at his profile..
