### ISSUE TITLE
Getting some errors on startup - 0f05fe0 update

### ISSUE THREAD

**Issue by blew1234** [mrk-its/homeassistant-blitzortung#39]
Hi there,
I'm getting some errors on startup with the latest version

Error unloading entry Blitzortung for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 134, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

Logger: homeassistant.setup
Source: setup.py:316
First occurred: 5:30:49 AM (1 occurrences)
Last logged: 5:30:49 AM

Unable to prepare setup for platform blitzortung.sensor: Platform not found (cannot import name 'DeviceEntryType' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).

Any ideas?

**Comment by L3cha1** [comment]
I am getting the same errors. I'm on 2021.11.5.

**Comment by blew1234** [comment]
2021.11.5 as well.

**Comment by blew1234** [comment]
Just upgraded to 2021.12.1 and it seems to be working again

**Comment by L3cha1** [comment]
I also upgraded to 2021.12.1 and it's fixed for me as well. thanks

**Comment by blew1234** [comment]
No problems.
