### ISSUE TITLE
Cant find Blitzortung in Hacs Anymore

### ISSUE THREAD

**Issue by yfands** [mrk-its/homeassistant-blitzortung#42]
After yesterdays update (dec. 12th 2021) Home assistant came back with the notification that Blitzortung could not be found, 
After deleting the integration and trying to install it again it cant ben found in HACS ???

edit:
Oops, my bad, after a restart Home Assistant didnt remove Blitzortung, so indeed Hacs wasnt able to find it in the downloadable section. After deleting and restating for the second time Blitzortung was indeed gone and I could install it again.

edit:
Me again, Integration with Hacs goes ok, but after restart Blitzortung cant be found in Configuration/Integrations

Regards
Frank

**Comment by SergioRius** [comment]
The integration is not available after adding the repository with HACS and restarting.

**Comment by mrk-its** [comment]
it looks it is available through HACS, closing.
