### ISSUE TITLE
cannot downgrade blitzortung

### ISSUE THREAD

**Issue by rocketdyke** [mrk-its/homeassistant-blitzortung#44]
inability to downgrade after installing latest version that fails on HASS 2021.11.05

**Comment by nepozs** [comment]
It is really significant problem, downgrade is possible, but it neeeds digging deep in history of repository.
@mrk-its It would be nice if releases could be tagged - it is really important for users to easy manage versions from HACS.

**Comment by mrk-its** [comment]
Just started creating releases, thanks for suggestion!
