### ISSUE TITLE
Entitees Not Avaiablr

### ISSUE THREAD

**Issue by mboroff** [mrk-its/homeassistant-blitzortung#48]
This interfac has stopped working. The three entitees are listed as unavailable.

**Comment by K5OZ** [comment]
Marty,
Mine is a little different.  It says unknown after about a half hour.  I also posted my issue (#49) 
I hope the community can get this fixed.
73,
Dave

**Comment by mboroff** [comment]
My production system says unknown and my test system says unavailable.

Marty

**Comment by alphachris** [comment]
see #49

**Comment by harry747400** [comment]
in that thread you mention clients.py but i can't find that file in my system. where is it?

**Comment by mboroff** [comment]
Blitzunortung is failing again. I have opened an issue.

Marty Boroff

**Comment by K5OZ** [comment]
Thanks Marty

**Comment by mboroff** [comment]
I was able to determine there was a firmware update for both the red and blue boards in Nov 2022. When I used the link for the socket I got a response of “update”. I suppose they may have change the handshake since the socket is still valid.
