### ISSUE TITLE
Integration not loading

### ISSUE THREAD

**Issue by belangp** [mrk-its/homeassistant-blitzortung#57]
I just installed via HACS and, after restarting HA, the integration doesn't appear in the Settings/Integrations page. I checked to make sure it's in the custom_components directory, and everything is fine. Tried installing manually too and it still doesn't show up in the integrations list.

**Comment by travi** [comment]
I found this integration today and it installed and is working properly for me

**Comment by belangp** [comment]
Interesting. After multiple restarts and switching browsers, it now works
