### ISSUE TITLE
entities are still unavailable.

### ISSUE THREAD

**Issue by harry747400** [mrk-its/homeassistant-blitzortung#62]
some time ago i installed blitzortung but i never got it to work. all i get is "unavailable" on all 3 entities

does it require MQTT? i have the MQTT add-on and a broker installed and configured, and they work.

is it a firewall issue? what IP address and port do i have to allow? no, pihole is not the issue, i checked.

**Comment by harry747400** [comment]
i'm still new to all this. can someone walk me through what i have to do? thanks.

**Comment by mrk-its** [comment]
I hope you finally got it working, closing as it is very old issue.
