### ISSUE TITLE
The name property of the Unit System is deprecated

### ISSUE THREAD

**Issue by epenet** [mrk-its/homeassistant-blitzortung#66]
As per https://github.com/home-assistant/core/pull/80257

The name of a unit system should never be used for checking its type. Instance checks should be used instead:

Correct:
```python
if hass.config.units is IMPERIAL_SYSTEM:
    pass

if hass.config.units is METRIC_SYSTEM:
    pass
```

Incorrect:
```python
if hass.config.units.name == CONF_UNIT_SYSTEM_IMPERIAL:
    pass

if hass.config.units.name == CONF_UNIT_SYSTEM_METRIC:
    pass
```

**Comment by epenet** [comment]
Note: the name of the `IMPERIAL_SYSTEM` is likely to get adjusted as soon as `2022.11` so this is an advance warning

**Comment by ocean75** [comment]
Note: 
Detected integration that accesses the `name` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for blitzortung using this method at custom_components/blitzortung/geo_location.py, line 100: if hass.config.units.name == CONF_UNIT_SYSTEM_IMPERIAL:

**Comment by codyc1515** [comment]
Seeing the same.

**Comment by kryptonitecb3** [comment]
+1
```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 10:06:59 AM (1 occurrences)
Last logged: 10:06:59 AM

Detected integration that accesses the `name` property of the unit system. This is deprecated and will stop working in Home Assistant 2023.1. Please adjust to use instance check instead.. Please report issue to the custom integration author for blitzortung using this method at custom_components/blitzortung/geo_location.py, line 100: if hass.config.units.name == CONF_UNIT_SYSTEM_IMPERIAL:
```

**Comment by jbonzey** [comment]
I am also seeing the same

**Comment by codyc1515** [comment]
This was fixed in https://github.com/mrk-its/homeassistant-blitzortung/pull/67 and can be closed now.
