### ISSUE TITLE
Service Never Starts

### ISSUE THREAD

**Issue by mdframe** [mrk-its/homeassistant-blitzortung#7]
After the latest update today the service never starts.  I am trying to get some details and logs but so far nothing for this add-in will work.  It was working prior to this update without issues.

**Comment by mrk-its** [comment]
Can you revert to latest version that was working for you and let me know it helps? For example:
`git checkout 364c2cdc1bae5b1897980c5d95868fcc3892dc6a` - I know it worked for you (I changed latitiude / longitude to lat/lon here)

**Comment by mdframe** [comment]
I was able to get the latest service to start and all entities are now working except clients connected.  It is showing undefined.  I restarted 6 times and the other entities showed.  Still not finding any clear evidence of why I had such a startup problem or why clients connected is undefined.

**Comment by mrk-its** [comment]
"Clients connected" sensor is now hidden by default, so it is expected.

**Comment by Larx** [comment]
@mdframe: DId you do anything special to get the integration working? I installed it (several times the last days) and simply nothing happens :-(.

**Comment by mrk-its** [comment]
@mdframe I've just pushed new version with fixed sensor behavior on start (sensors should be available as soon as connection to server is established)

**Comment by mrk-its** [comment]
@Larx did you add "Blitzortung" on HomeAssistant's `Configuration/Integrations` page?

**Comment by Larx** [comment]
No, I didn't. I missed out the fact that it's not enough to add with HACS, sorry...

**Comment by mdframe** [comment]
I am testing now.

**Comment by mdframe** [comment]
That started right up.  Only 3 entities right?

**Comment by Larx** [comment]
Only an error for me. What is this "paho" I am missing?

Protokolldetails ( ERROR )
Logger: homeassistant.config_entries
Source: custom_components/blitzortung/mqtt.py:99
First occurred: 16:21:17 (2 occurrences)
Last logged: 16:50:52
```

Error setting up entry Blitzortung for blitzortung
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config_entries.py", line 220, in async_setup
    hass, self
  File "/srv/homeassistant_data/homeassistant/custom_components/blitzortung/__init__.py", line 64, in async_setup_entry
    server_stats=config.get(const.SERVER_STATS),
  File "/srv/homeassistant_data/homeassistant/custom_components/blitzortung/__init__.py", line 168, in __init__
    self.mqtt_client = MQTT(hass, "blitzortung.ha.sed.pl", 1883,)
  File "/srv/homeassistant_data/homeassistant/custom_components/blitzortung/mqtt.py", line 99, in __init__
    import paho.mqtt.client as mqtt  # pylint: disable=import-outside-toplevel
ModuleNotFoundError: No module named 'paho'
```

**Comment by mrk-its** [comment]
@mdframe yes, it provides 3 sensors

**Comment by mrk-its** [comment]
@Larx - ha, thanks, I'll add it to component's requirements (it is required by standard 'mqtt' component of home assistant, so most of users probably already have it). I'll push fix in few minutes

**Comment by mrk-its** [comment]
@Larx done, could you reinstall component?

**Comment by mdframe** [comment]
Everything looks good!

**Comment by Larx** [comment]
OK - three entities found, thanks.
