### ISSUE TITLE
Blitzortung Not working Again

### ISSUE THREAD

**Issue by mboroff** [mrk-its/homeassistant-blitzortung#70]
The site must have changed access again. My card shows unknown again.
<img width="1307" alt="Screenshot 2023-01-12 at 12 56 35 PM" src="https://user-images.githubusercontent.com/7621866/212143070-f90549e1-fadc-41f0-a3b3-cdf992b8458f.png">

**Comment by K5OZ** [comment]
Marty,
I have the same issue; however, I am using a direct call to the web socket (wss:ws7.blitzortung.org/) to get the data.   It connects, but no data is being sent after the query in node red.
Thanks for opening this problem ticket.
Dave

**Comment by fordemon92** [comment]
Having the same issue worked about a week ago and now it's not.

**Comment by anderbak** [comment]
Same here

**Comment by mrk-its** [comment]
It looks they changed magic constant that needs to be sent on start, it should work again.

**Comment by mboroff** [comment]
What is the new code?MartySent from my iPhoneOn Jan 14, 2023, at 6:52 PM, Mariusz Kryński ***@***.***> wrote:﻿
It looks they changed magic constant that needs to be sent on start, it should work again.

**Comment by mrk-its** [comment]
commited here: https://github.com/mrk-its/homeassistant-blitzortung/commit/45ed1a29389f16714c253308d792420aedeee901

**Comment by K5OZ** [comment]
Thank you Mariusz !!!

**Comment by mboroff** [comment]
Thank you Mariusz. I had a feeling it was something like this.

May I ask how you arrived at the new value? Is there documentation you were able to obtain?

Marty

**Comment by mrk-its** [comment]
> May I ask how you arrived at the new value?

Open chrome (or firefox) dev tools, on network tab filter only web socket connections and reload https://www.blitzortung.org/ - you should be able to see first message sent from browser - it contains the value.

**Comment by mboroff** [comment]
Got it Thanks so much.

Marty
