### ISSUE TITLE
Blitzortung not working, but no error message

### ISSUE THREAD

**Issue by der-optimist** [mrk-its/homeassistant-blitzortung#75]
My blitzortung does not work any more - the sensors are created, log file seems normal (connection to MQTT server is established), but in case of a thunderstorm nearby the sensors stay unknown and the counter stays at 0. 
I tried re-install and also adding a second instance with standard config. Even with radius 100 km no lightnings are counted (lot of lightnings happened in that radius. I hear them and I see them on blitzortung.org).
Is there any advice what I could try?

![image](https://github.com/mrk-its/homeassistant-blitzortung/assets/45357614/e4d58981-01d9-4165-97af-a84141743a05)

I'm using Home Assistant 2023.7.1

**Comment by Stephan1202** [comment]
It is the same for me. I did not change anything, but Blitzortung stopped showing data.
Version 1.3.1
HA 2023.5.3

**Comment by garethhowell** [comment]
I'm glad it's not just me :-)

**Comment by ktn7419** [comment]
There is a problem. See message #74.

**Comment by Stephan1202** [comment]
It is working again, at least at my end,

**Comment by der-optimist** [comment]
Yes, also here it's working again. Thanks for repairing

**Comment by der-optimist** [comment]
Working again
