### ISSUE TITLE
deprecated constant in HA 2024.1

### ISSUE THREAD

**Issue by Mariusthvdb** [mrk-its/homeassistant-blitzortung#79]
Please see below error and update accordingly

Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 00:16:57 (10 occurrences)
Last logged: 00:17:09

LENGTH_KILOMETERS was used from blitzortung, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.KILOMETERS instead, please create a bug report at https://github.com/mrk-its/homeassistant-blitzortung/issues
LENGTH_MILES was used from blitzortung, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.MILES instead, please create a bug report at https://github.com/mrk-its/homeassistant-blitzortung/issues

the fix is like this: https://github.com/golles/ha-knmi/pull/112/files

**Comment by JavanXD** [comment]
```
Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 29. Februar 2024 um 22:24:46 (6 occurrences)
Last logged: 29. Februar 2024 um 22:24:57

TEMP_CELSIUS was used from local_luftdaten, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/lichtteil/local_luftdaten/issues
LENGTH_KILOMETERS was used from blitzortung, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.KILOMETERS instead, please create a bug report at https://github.com/mrk-its/homeassistant-blitzortung/issues
LENGTH_MILES was used from blitzortung, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.MILES instead, please create a bug report at https://github.com/mrk-its/homeassistant-blitzortung/issues
```

**Comment by milandzuris** [comment]
@mrk-its
