### ISSUE TITLE
Disconnected from MQTT server

### ISSUE THREAD

**Issue by holdestmade** [mrk-its/homeassistant-blitzortung#8]
Get this error when adding the integration and all entities are shown as Unknown, have tried a restart

HA 0.112, v6f843e3 of this integration

```
Log Details (WARNING)
Logger: custom_components.blitzortung.mqtt
Source: custom_components/blitzortung/mqtt.py:308
Integration: Blitzortung (documentation, issues)
First occurred: 10:56:00 (1 occurrences)
Last logged: 10:56:00

Disconnected from MQTT server blitzortung.ha.sed.pl:1883 (0)
```

EDIT:

After 10 minutes or so, the counter has gone to 0, I assume Unknown in the other 2 sensors is because there is no lightning at my location (UK)  ?

**Comment by mrk-its** [comment]
@holdestmade yes, exactly. But I'll fix the counter sensor (I will set it to 0 instantly, current behavior is very confusing).

**Comment by holdestmade** [comment]
OK, thanks, still get the above error in my log on reboot of HA

**Comment by pinkywafer** [comment]
if I set my radius to a lsrge area (eg 5000) I'm getting the flashes listed etc.  If I have it set only to the area I'm interested in (ie 100km from location) counter shows 0, azimuth and distance both show `unknown`  in this circumstance (ie no lightning detected nearby) could the state of azimuth and distance both be something like `none detected` instead of unknown

**Comment by mrk-its** [comment]
@holdestmade I've just released new version with bunch of changes:
 * sensors behavior on start is fixed - they should be available as soon as connection to server is established, lightning counter should be set to 0, azimuth and distance to None (HA should render them as "Unknown")
* I've decreased log level of server disconnection messages to `info`, so they should be less disturbing (as said before periodic disconnects are expected, component should reconnect automatically after that).

**Comment by mrk-its** [comment]
@holdestmade I don't think mixing text and numeric state in single sensor is good idea. You can probably easy achieve that using template sensor.

**Comment by holdestmade** [comment]
All working now after upgrade, thank you.
