### ISSUE TITLE
LENGTH_KILOMETERS and LENGTH_MILES will be deprecated in HA Core 2025.1.

### ISSUE THREAD

**Issue by aubierr** [mrk-its/homeassistant-blitzortung#82]
Good morning,

I am pointing out this which is showing up as a warning in the logs.
Is it possible to update?

LENGTH_KILOMETERS was used from blitzortung, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.KILOMETERS instead

LENGTH_MILES was used from blitzortung, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.MILES instead

Thank you

**Comment by tomlut** [comment]
Duplicate of https://github.com/mrk-its/homeassistant-blitzortung/issues/79

**Comment by mrk-its** [comment]
fixed by #81
