### ISSUE TITLE
Error in integration 

### ISSUE THREAD

**Issue by craigmate** [mrk-its/homeassistant-blitzortung#83]
Hi..

I have been getting the following error for the last few hours

This error originated from a custom integration.

Logger: custom_components.blitzortung.mqtt
Source: custom_components/blitzortung/mqtt.py:233
Integration: Blitzortung (documentation, issues)
First occurred: 11:00:07 (102 occurrences)
Last logged: 14:02:41

Unable to connect to the MQTT broker: Connection Refused: not authorised.

**Comment by stevehop** [comment]
Have also started seeing this today

**Comment by craigmate** [comment]
I logged a similar error (Error #26) back in June 2021, and the owner asked me to use dig blitzortung.ha.sed.pl
I did run this when I first saw the error an it wasn't resolving
However, I ran it again and it appears to be resolving the DNS
See the screenshot below

![image](https://github.com/mrk-its/homeassistant-blitzortung/assets/51873021/b174ada8-faa8-472a-97e7-1bb5417ba9e6)

The intergration appears to be working again now.  So not sure if it was an issue with DNS or the MQTT server which it connects to

**Comment by Tiger2205** [comment]
Managed to check on DNS. You have right! It was resolving 0.0.0.0

adblocker thought it is ads

i whitelisted it and it appears again. 
thx for the tip

**Comment by stevehop** [comment]
Looks like it's sorted itself, I use AdGuard but without whitelisting the DNS name it's started working again so maybe it found it's way onto a filter list and subsequently got removed
