### ISSUE TITLE
Detected that custom integration 'blitzortung' calls async_write_ha_state from a thread at custom_component

### ISSUE THREAD

**Issue by haaino** [mrk-its/homeassistant-blitzortung#96]
Hi,

I just installed HA 2024.5 and noticed the following message in the logile (see below). Hopefully this means something for someone.

-----

Detected that custom integration 'blitzortung' calls async_write_ha_state from a thread at custom_components/blitzortung/__init__.py, line 222: sensor.async_write_ha_state(), please report it to the author of the 'blitzortung' custom integration

----

Best regards,
Haaino

**Comment by mrk-its** [comment]
Can you check on 1.3.3? Thanks!

**Comment by haaino** [comment]
Thx!
